### PR TITLE
Fix empty members

### PR DESCRIPTION
**Pull request by MrMonk3y**
I quickly needed to fix two bugs I encountered using the script. There are nicer ways to handle those problems for sure. Works for me though. Thanks a lot for the script! The only one that worked for me so far.

### CODE REVIEW

**Comment by codeforkjeff** [comment]
These are really good changes! Thank you for this pull request, I appreciate your work!

**Comment by codeforkjeff** [comment]
@MrMonk3y While trying out your branch, I noticed that each time you run the `generate_html` step without deleting all the files in the html directory first, it will keep creating files named _2, _3, etc for the same chat.

There's already a mechanism in place to deal with long filenames by truncating the base filename and appending a short hash. I wonder if we can modify that to always append a short hash, and to generate the hash on the chat id. This way, the mapping of any given chat -> html output file will be stable.

Thoughts? I'm happy to make this change after merging this request.

**Comment by MrMonk3y** [comment]
You are right. That was kinda obvious, should have seen it comming, sorry :) The while loop counter looks ugly anyway. Maybe a unique identifier from the chat could be appended instead. Technically the member names are still within the messages just not in the header of the chat. We could extract the names from there which would resolve the issues of people who left teams. I'm not sure about this though. I wonder if there could be situations where multiple chats with the same participants could exist. Also, in the rare case of people having the same name it would overwrite chats.

**Comment by codeforkjeff** [comment]
I thought about this some more. I think the base filename of each .html file should be the chat id. This is how chats are named in the data directory. It keeps the filenames very stable, and it also solves the somewhat ugly solution that was in place, to deal with very long filenames.

The script should also generate an `index.html` containing links to the individual chats, with human readable names for the link text. This way we can continue to adjust or refine the `get_chat_name` function without affecting anything else.

I'm going to merge this request and then make the above changes.

**Pull request merged**
